<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - UrbanSetu</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<style type="text/css">
					body {
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						color: #333;
						margin: 0;
						padding: 40px;
                        background: #f8fafc;
					}
					.container {
						max-width: 1000px;
						margin: 0 auto;
						background: #fff;
						padding: 30px;
						border-radius: 12px;
						box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
					}
					h1 {
						color: #1e293b;
						font-size: 28px;
						margin-bottom: 10px;
					}
					p {
						color: #64748b;
						font-size: 15px;
						line-height: 1.6;
                        margin-bottom: 20px;
					}
					a {
						color: #3b82f6;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					table {
						width: 100%;
						border-collapse: collapse;
						margin-top: 20px;
					}
					th {
						text-align: left;
						padding: 12px;
						background: #f1f5f9;
						border-bottom: 2px solid #e2e8f0;
						color: #475569;
						font-weight: 600;
						text-transform: uppercase;
						font-size: 12px;
						letter-spacing: 0.05em;
					}
					td {
						padding: 12px;
						border-bottom: 1px solid #e2e8f0;
						color: #334155;
						font-size: 14px;
					}
					tr:hover td {
						background: #f8fafc;
					}
					.count {
						background: #e0f2fe;
						color: #0369a1;
						padding: 2px 8px;
						border-radius: 4px;
						font-weight: 600;
						font-size: 12px;
					}
				</style>
			</head>
			<body>
				<div class="container">
					<h1>XML Sitemap</h1>
					<p>This XML Sitemap is generated by <strong>UrbanSetu</strong> to make your content more visible for search engines.<br/>
					For more information, visit <a href="https://sitemaps.org">sitemaps.org</a>.</p>
					
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
						<p>Number of sitemaps in this index: <span class="count"><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></span></p>
						<table>
							<thead>
								<tr>
									<th>Sitemap URL</th>
									<th>Last Modified</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<tr>
										<td>
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), concat(' ', substring(sitemap:lastmod, 12, 5)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
					
					<xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
						<p>Number of URLs in this sitemap: <span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></span></p>
						<table>
							<thead>
								<tr>
									<th>URL</th>
									<th>Last Modified</th>
									<th>Change Frequency</th>
									<th>Priority</th>
								</tr>
							</thead>
							<tbody>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
										<td>
											<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod, 0, 11), concat(' ', substring(sitemap:lastmod, 12, 5)))"/>
										</td>
										<td>
											<xsl:value-of select="sitemap:changefreq"/>
										</td>
										<td>
											<xsl:value-of select="sitemap:priority"/>
										</td>
									</tr>
								</xsl:for-each>
							</tbody>
						</table>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
